version: '3.6'
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg11
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - 5432:5432

    environment:
      POSTGRES_PASSWORD: postgres