# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search_request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import corpus_pb2 as corpus__pb2

from corpus_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='search_request.proto',
  package='hsz.foo.search_request',
  syntax='proto3',
  serialized_options=_b('Z\021hsz_foo/schema_pb'),
  serialized_pb=_b('\n\x14search_request.proto\x12\x16hsz.foo.search_request\x1a\x0c\x63orpus.proto\"\xf4\x01\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x13\n\x0bpage_number\x18\x02 \x01(\x05\x12\x17\n\x0fresult_per_page\x18\x03 \x01(\x05\x12&\n\x06\x63orpus\x18\x04 \x01(\x0e\x32\x16.hsz.foo.corpus.Corpus\x12\x0c\n\x04uids\x18\x05 \x03(\x05\x12\x41\n\x06weight\x18\x06 \x03(\x0b\x32\x31.hsz.foo.search_request.SearchRequest.WeightEntry\x1a-\n\x0bWeightEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x42\x13Z\x11hsz_foo/schema_pbP\x00\x62\x06proto3')
  ,
  dependencies=[corpus__pb2.DESCRIPTOR,],
  public_dependencies=[corpus__pb2.DESCRIPTOR,])




_SEARCHREQUEST_WEIGHTENTRY = _descriptor.Descriptor(
  name='WeightEntry',
  full_name='hsz.foo.search_request.SearchRequest.WeightEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='hsz.foo.search_request.SearchRequest.WeightEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='hsz.foo.search_request.SearchRequest.WeightEntry.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=307,
)

_SEARCHREQUEST = _descriptor.Descriptor(
  name='SearchRequest',
  full_name='hsz.foo.search_request.SearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='hsz.foo.search_request.SearchRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_number', full_name='hsz.foo.search_request.SearchRequest.page_number', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result_per_page', full_name='hsz.foo.search_request.SearchRequest.result_per_page', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='corpus', full_name='hsz.foo.search_request.SearchRequest.corpus', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uids', full_name='hsz.foo.search_request.SearchRequest.uids', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weight', full_name='hsz.foo.search_request.SearchRequest.weight', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SEARCHREQUEST_WEIGHTENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=307,
)

_SEARCHREQUEST_WEIGHTENTRY.containing_type = _SEARCHREQUEST
_SEARCHREQUEST.fields_by_name['corpus'].enum_type = corpus__pb2._CORPUS
_SEARCHREQUEST.fields_by_name['weight'].message_type = _SEARCHREQUEST_WEIGHTENTRY
DESCRIPTOR.message_types_by_name['SearchRequest'] = _SEARCHREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SearchRequest = _reflection.GeneratedProtocolMessageType('SearchRequest', (_message.Message,), {

  'WeightEntry' : _reflection.GeneratedProtocolMessageType('WeightEntry', (_message.Message,), {
    'DESCRIPTOR' : _SEARCHREQUEST_WEIGHTENTRY,
    '__module__' : 'search_request_pb2'
    # @@protoc_insertion_point(class_scope:hsz.foo.search_request.SearchRequest.WeightEntry)
    })
  ,
  'DESCRIPTOR' : _SEARCHREQUEST,
  '__module__' : 'search_request_pb2'
  # @@protoc_insertion_point(class_scope:hsz.foo.search_request.SearchRequest)
  })
_sym_db.RegisterMessage(SearchRequest)
_sym_db.RegisterMessage(SearchRequest.WeightEntry)


DESCRIPTOR._options = None
_SEARCHREQUEST_WEIGHTENTRY._options = None
# @@protoc_insertion_point(module_scope)
