version: '3.6'
services:
  postgres:
    image: postgres:11
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - 5432:5432
    # volumes:
    #   - postgresql-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"

  # volumes:
  #   postgresql-volume:
  #     external: true